name: Generate index

on:
  push:
    branches: 'main'
    paths:
      - 'localized_data/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: release
          fetch-depth: 0

      - name: Merge changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git merge -X theirs origin/main

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create index
        run: python gen_index.py

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update index
          branch: release
          file_pattern: 'index.json'

      - name: Send update to downstream repositories
        env:
          UPD_TOKEN: ${{ secrets.NOTIFY_REPO }} # Đã sửa thành secrets.UPD_TOKEN
          REPO_LIST: ${{ vars.NOTIFY_REPO }}
          REPO_OWNER: ${{ github.repository_owner }}
          CURRENT_REPO: ${{ github.event.repository.name }}
        run: |
          # Kiểm tra nếu biến REPO_LIST bị trống
          if [ -z "$REPO_LIST" ]; then
            echo "⚠️ [LOG]: Biến NOTIFY_REPO chưa được thiết lập hoặc trống. Bỏ qua gửi update."
            exit 0
          fi

          if [ -z "$UPD_TOKEN" ]; then
            echo "❌ [LOG]: Secret UPD_TOKEN bị trống hoặc chưa được cấu hình!"
            exit 1
          fi

          IFS=',' read -r -a repos <<< "$REPO_LIST"
          for target_repo in "${repos[@]}"; do
            target_repo=$(echo "$target_repo" | xargs)
            
            if [ -n "$target_repo" ]; then
              echo "🚀 Sending trigger signal to: $REPO_OWNER/$target_repo với event_type: $CURRENT_REPO"
              
              RESPONSE=$(curl -L -s -o /dev/null -w "%{http_code}" -X POST \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer $UPD_TOKEN" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/$REPO_OWNER/$target_repo/dispatches \
                -d "{\"event_type\": \"$CURRENT_REPO\", \"client_payload\": {\"ref\": \"main\"}}")
                
              if [ "$RESPONSE" -eq 204 ]; then
                echo "✅ Triggered $target_repo successfully (HTTP 204)."
              else
                echo "❌ Failed to trigger $target_repo. Received HTTP status: $RESPONSE"
              fi
            fi
          done